version: '2'

services:
  redis:
    image: redis:2.8
    container_name: redis
    restart: always
    networks:
      - backend

  solr:
    build: ./solr
    container_name: solr
    ports:
      - '8983:8983'
    networks:
      - backend

  mongodb:
    image: mongo:2.6.12
    command: mongod --dbpath /data/db --smallfiles
    networks:
      - backend

  manager:
    build: ./manager
    command: bundle exec rails s -p 3000
    ports:
      - '3001:3000'
    container_name: manager
    restart: always
    depends_on:
      - mongodb
      - api
    networks:
      - backend
    environment:
      WORKER_HOST: http://worker:3000
      WORKER_API_KEY: workerkey
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017

  worker:
    build: ./worker
    command: bundle exec rails s -p 3000
    ports:
      - '3002:3000'
    container_name: worker
    restart: always
    depends_on:
      - redis
      - mongodb
      - sidekiq
      - api
    networks:
      - backend
    environment:
      MANAGER_HOST: http://manager:3000
      MANAGER_API_KEY: managerkey
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017
      REDIS_HOST: redis://redis:6379/0

  sidekiq:
    build: ./worker
    command: bundle exec sidekiq
    container_name: sidekiq
    restart: always
    depends_on:
      - redis
      - mongodb
      - api
    networks:
      - backend
    environment:
      MANAGER_HOST: http://manager:3000
      MANAGER_API_KEY: managerkey
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017
      REDIS_HOST: redis://redis:6379/0

  api:
    build: ./api
    command: bundle exec rails s -p 3000
    ports:
      - '3000:3000'
    container_name: api
    restart: always
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      MONGOID_HOSTS: mongodb:27017
      SOLR_PING: http://solr:8983/solr/admin/ping
      SOLR_URL: http://solr:8983/solr
      WORKER_API_URL: http://worker:3000
      HARVESTER_IPS: '172.19.0.8, 172.19.0.6, 0.0.0.0, 127.0.0.1, 192.168.99.100, localhost'

volumes:
  mongodb:

networks:
  backend:

