version: '3.7'

services:
  redis:
    image: redis:2.8
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - 6379:6379

  mongodb:
    image: mongo:3.6.8
    command: mongod
    volumes:
      - mongodb:/data/db
    networks:
      backend:
        aliases:
          - mongodb
  manager:
    build: ./manager
    command: bundle exec rails s -p 3001
    ports:
      - '3001:3001'
    container_name: manager
    restart: always
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      WORKER_KEY: JK54SFJ94DAQQCB
      WORKER_HOST: http://worker:3002
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017
      HARVESTER_API_KEY: KJ64DC023FFO

  worker:
    build: ./worker
    command: bundle exec rails s -p 3002
    ports:
      - '3002:3002'
    container_name: worker
    restart: always
    depends_on:
      - redis
      - mongodb
      - api
    networks:
      - backend
    environment:
      WORKER_KEY: JK54SFJ94DAQQCB
      MANAGER_HOST: http://manager:3000
      HARVESTER_API_KEY: KJ64DC023FFO
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    build: ./worker
    command: bundle exec sidekiq
    container_name: sidekiq
    restart: always
    depends_on:
      - redis
      - mongodb
      - api
      - worker
    networks:
      - backend
    environment:
      MANAGER_HOST: http://manager:3000
      MANAGER_API_KEY: KJ64DC023FFO
      API_HOST: http://api:3000
      API_MONGOID_HOSTS: mongodb:27017
      REDIS_URL: redis://redis:6379/0

  api:
    build: ./sample_rails_api
    command: bundle exec rails s -p 3000
    ports:
      - '3000:3000'
    container_name: api
    restart: always
    depends_on:
      - redis
      - solr
      - mongodb
    networks:
      - backend
    environment:
      API_MONGOID_HOSTS: mongodb:27017
      SOLR_PING: http://solr:8983/solr/admin/ping
      SOLR_URL: http://solr:8983/solr
      WORKER_API_URL: http://worker:3000
      REDIS_URL: redis://redis:6379/0

  solr:
    build: ./sample_rails_api
    container_name: solr
    command: bundle exec rake sunspot:solr:run
    ports:
      - '8982:8982'
    networks:
      - backend

  sidekiq-api:
    build: ./sample_rails_api
    command: bundle exec sidekiq
    container_name: sidekiq-api
    restart: always
    depends_on:
      - redis
      - mongodb
      - api
    networks:
      - backend
    environment:
      API_MONGOID_HOSTS: mongodb:27017
      SOLR_PING: http://solr:8983/solr/admin/ping
      SOLR_URL: http://solr:8983/solr
      WORKER_API_URL: http://worker:3000
      REDIS_URL: redis://redis:6379/0


  # resque:
  #   build: ./api
  #   command: bundle exec rake environment resque:workers QUEUE=solr_index COUNT=3
  #   container_name: resque
  #   restart: always
  #   depends_on:
  #     - redis
  #     - solr
  #     - mongodb
  #     - api
  #   networks:
  #     - backend
  #   environment:
  #     MONGOID_HOSTS: mongodb:27017
  #     SOLR_PING: http://solr:8983/solr/admin/ping
  #     SOLR_URL: http://solr:8983/solr
  #     WORKER_API_URL: http://worker:3000
  #     REDIS_URL: redis://redis:6379/0

  # scheduler:
  #   build: ./api
  #   command: rake resque:scheduler
  #   container_name: scheduler
  #   restart: always
  #   depends_on:
  #     - redis
  #     - solr
  #     - mongodb
  #     - api
  #   networks:
  #     - backend
  #   environment:
  #     MONGOID_HOSTS: mongodb:27017
  #     SOLR_PING: http://solr:8983/solr/admin/ping
  #     SOLR_URL: http://solr:8983/solr
  #     WORKER_API_URL: http://worker:3000
  #     REDIS_URL: redis://redis:6379/0

volumes:
  mongodb:

networks:
  backend:
