# -------------------------------- 
# Services
# -------------------------------- 
redis:
  image: redis:2.8
  container_name: redis
  ports:
    - '6379:6379'
  restart: always
sidekiq:
  build: ./worker
  command: bundle exec sidekiq
  container_name: sidekiq
  restart: always
  environment:
    REDIS_HOST: redis.weave.local
# solr:
#   image: makuk66/docker-solr:4.10.4
#   ports:
#     - '8983:8983'
#   container_name: solr
solr:
  build: ./solr
  ports:
    - '8983:8983'
  container_name: solr
mongodb:
  build: ./mongodb
  container_name: mongodb
  volumes:
    - ./data/db:/data/db

# -------------------------------- 
# Applications
# -------------------------------- 
api:
  build: ./api
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - '3000:3000'
  container_name: api
  restart: always
  environment:
    MONGOID_HOSTS: mongodb.weave.local:27017
    SOLR_PING: http://solr.weave.local:8983/solr/admin/ping
    SOLR_URL: http://solr.weave.local:8983/solr
    WORKER_API_URL: http://worker.weave.local:3000
    HARVESTER_IPS: 'worker.weave.local, manager.weave.local'
manager:
  build: ./manager
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - '3001:3000'
  container_name: manager
  restart: always
  environment:
    WORKER_HOST: http://worker.weave.local:3000
    WORKER_API_KEY: workerkey
    API_HOST: http://api.weaver.local:3000
    API_MONGOID_HOSTS: mongodb.weave.local:27017
worker:
  build: ./worker
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - '3002:3000'
  container_name: worker
  restart: always
  environment:
    MANAGER_HOST: http://manager.weave.local:3000
    MANAGER_API_KEY: managerkey
    API_HOST: http://api.weave.local:3000
    API_MONGOID_HOSTS: mongodb.weave.local:27017
