# -------------------------------- 
# Services
# -------------------------------- 
redis:
  image: redis:2.8
  container_name: redis
  ports:
    - '6379:6379'
  restart: always
sidekiq:
  build: ./worker
  command: bundle exec sidekiq
  container_name: sidekiq
  restart: always
  environment:
    REDIS_HOST: redis.weave.local
mongodb:
  build: ./mongodb
  container_name: mongodb
  volumes:
    - ./data/db:/data/db

# -------------------------------- 
# Applications
# -------------------------------- 
manager:
  build: ./manager
  command: "bundle exec rails s -p 3000 -b '0.0.0.0' && rake docker:seed"
  ports:
    - '3001:3000'
  container_name: manager
  restart: always
worker:
  build: ./worker
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - '3002:3000'
  container_name: worker
  restart: always

