

development:
  clients:
    default:
      database: supplejack_api_development1
      hosts:
        - <%= ENV['API_MONGOID_HOSTS'] %>

    strong:
      database: supplejack_api_development1
      hosts:
        - <%= ENV['API_MONGOID_HOSTS'] %>
