

development:
  solr:
    hostname: localhost
    port: 8982
    path: /solr
    log_level: INFO

test:
  solr:
    hostname: solr
    port: 8983
    path: /solr
    log_level: DEBUG
    solr_home: solr

# production:
#   solr:
#     hostname: localhost
#     port: 8983
#     log_level: WARNING
#     # read_timeout: 2solr
#     # open_timeout: 0.5

# staging:
#   solr:
#     hostname: localhost
#     port: 8080
#     path: '/solr4'
#     log_level: WARNING 
#     pid_dir: '/var/run/tomcat'
#     auto_commit_after_request: false
